# Generated by Django 5.2.5 on 2025-09-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meatshop', '0002_historicalincomesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincomesale',
            name='is_perexod',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='historicalincomesale',
            name='perexod_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incomesale',
            name='is_perexod',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='incomesale',
            name='perexod_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
