# Generated by Django 5.2.5 on 2025-09-03 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meatshop', '0004_alter_historicalincomesale_in_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincomesale',
            name='from_where',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalincomesale',
            name='to_where',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomesale',
            name='from_where',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomesale',
            name='to_where',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
